# Generated by Django 4.1.4 on 2022-12-23 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 23, 14, 37, 9, 104677))),
                ('modified_at', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('admin', 'administrator'), ('user', 'user')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 23, 14, 37, 9, 104677))),
                ('modified_at', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='AdditionalUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture_url', models.ImageField(blank=True, null=True, upload_to='images/profile-pictures/')),
                ('birth_year', models.IntegerField(default=2000)),
                ('date_registred', models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 23, 14, 37, 9, 104677))),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 23, 14, 37, 9, 104677))),
                ('modified_at', models.DateTimeField(blank=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.gender')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.roles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'additional_user_data',
            },
        ),
    ]
